apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quarkus-artifactory-tekton 
  janus-idp.io/tekton: quarkus-artifactory-tekton
  backstage.io/kubernetes-id: quarkus-artifactory-tekton
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quarkus-artifactory-tekton
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml