apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: quarkus-artifactory-tekton
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-artifactory-tekton 
  name: quarkus-artifactory-tekton
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: quarkus-artifactory-tekton
    weight: 100 
